services:
  vol2:
    build: ./volatility2
    container_name: volatility2
    volumes:
      - ./dumps:/dumps
      - ./output:/output
    stdin_open: true
    tty: true

  vol3:
    build: ./volatility3
    container_name: volatility3
    volumes:
      - ./dumps:/dumps
      - ./output:/output
      - ./cache:/root/.cache/volatility3
      - ./symbols:/root/.volatility3/symbols
    stdin_open: true
    tty: true
