FROM python:3.10-slim

WORKDIR /app

RUN apt update && apt install git vim curl wget build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev -y

RUN git clone https://github.com/volatilityfoundation/volatility.git
RUN curl http://pyenv.run | bash

WORKDIR /
COPY python2.sh .
CMD ["/bin/bash"]
